[[mgr.prepend_keymap]]
on   = [ "<C-h>" ]
run  = "hidden toggle"
desc = "Toggle hidden files"

[[mgr.prepend_keymap]]
on   = [ "<C-c>" ]
run  = 'shell "osascript -e \"tell application \\\"System Events\\\" to keystroke return using command down\" && drag \"$@\"" --confirm --orphan'
desc = "Drag selected files"

[[mgr.prepend_keymap]]
on = [ "z" ]
run = "plugin zoxide"

[[mgr.prepend_keymap]]
on = [ "Z" ]
run = "plugin fzf"

[[mgr.prepend_keymap]]
on = ["c", "c"]
run = "plugin copy-path-tilde"
desc = "Copy file path with ~ for home"
