[opener]
play = [
	{ run = 'open "$@"', orphan = true, for = "macos" },
]
vimd = [
	{ run = 'nvim -c "autocmd User VeryLazy PeekOpen" "$@"', block = true },
]

[open]
prepend_rules = [
	{ name = "*.md", use = "vimd" },
]
